# server(embbeded tomcat) config
server:
  port: 61208

# spring config
spring:
  servlet:
      multipart:
        max-file-size: 10GB
        max-request-size: 10GB
  nas:
    path:   c:/nas/crm/
    url:    https://files.ceragem.com/crm/
  jwt:
    secret: tpfkwpadnsdudzl
    auth-validation : true
  datasource:
    crm:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:oracle:thin:@172.23.1.91:8122:DCRMDB
      username: crmcon
      password: ENC(wKJa83sqiXSjBc/BKbqULw==)
#      url: jdbc:log4jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=glcmdb51p)(PORT=51401))(ADDRESS=(PROTOCOL=TCP)(HOST=glcmdb52p)(PORT=51401))(LOAD_BALANCE=OFF)(FAILOVER=ON))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=PCRMDB)))
#      username: CRMCON
#      password: ENC(tXsLiMFNX9RxlhodmsaY15Pgi9GF15rb)
      # Pool
      hikari:
        connection-timeout: 10000
        maximum-pool-size: 3
    
# log config
logging:
  #  file: logs/application.log
  config: classpath:logback-local.xml

# swagger config    
springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  server-url : http://localhost:61208/
  swagger-ui:
    path: /ceragem/
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
  

    
jasypt:
  encryptor:
    bean: jasyptStringEncryptor    
    


# bos config
bos:
  api:
    rest-url: https://mapone.ceragem.com
    rental-url: https://vhcgzds4ci.pce.ceragem.com:44300/api/web?sap-client=200
    rental-id: ENC(WaAHyP8Iq1t5h9SqqF5ONA==)
    rental_pwd: ENC(E3Szr9liKfsziIBcIOuL0Sop7VFsAWbvX12DEtVMLZReXpTviCcakmRnvusFvWz6OMV+ZU9aYaw=)
  use-event: true

