# server(embbeded tomcat) config
server:
  port: 61208
  tomcat:
    accesslog:
      enabled: true
      directory: /log/sw/tomcat/api
  
# spring config
spring:
#  servlet:
#      multipart:
#        max-file-size: 10GB
#        max-request-size: 10GB
  nas:
    path:   /NFS/crm/
    url:    https://files.ceragem.com/crm/
  jwt:
    secret: 1qaz@WSX
    auth-validation : true
  datasource:
    crm:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:oracle:thin:@172.23.1.91:8122:DCRMDB
      username: crmcon
      password: ENC(wKJa83sqiXSjBc/BKbqULw==)
      # Pool
      hikari:
        connection-timeout: 10000
        maximum-pool-size: 20
    
# log config
logging:
  #  file: logs/application.log
  config: classpath:logback-dev.xml

# swagger config    
springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs    
  server-url : https://dev-api.ceragem.com/
  swagger-ui:
    path: /ceragem/
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha

jasypt:
  encryptor:
    bean: jasyptStringEncryptor    
    

# bos config
bos:
  api:
    rest-url: https://mapone.ceragem.com
    rental-url: https://vhcgzds4ci.pce.ceragem.com:44300/api/web?sap-client=200
    rental-id: ENC(WaAHyP8Iq1t5h9SqqF5ONA==)
    rental_pwd: ENC(E3Szr9liKfsziIBcIOuL0Sop7VFsAWbvX12DEtVMLZReXpTviCcakmRnvusFvWz6OMV+ZU9aYaw=)
  use-event: true
