# server(embbeded tomcat) config
server:
  port: 8082
  tomcat:
    accesslog:
      enabled: true
      directory: /log/sw/tomcat/api
  
# spring config
spring:
  nas:
    path:   /NFS/crm/
    url:    https://files.ceragem.com/crm/
  jwt:
    secret: 1qaz@WSX
    auth-validation : true
  datasource:
    crm:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=glcmdb51p)(PORT=51401))(ADDRESS=(PROTOCOL=TCP)(HOST=glcmdb52p)(PORT=51401))(LOAD_BALANCE=OFF)(FAILOVER=ON))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=PCRMDB)))
      username: CRMCON
      password: ENC(tXsLiMFNX9RxlhodmsaY15Pgi9GF15rb)
      # Pool
      hikari:
        connection-timeout: 10000
        maximum-pool-size: 50
   
# log config
logging:
  #  file: logs/application.log
  config: classpath:logback-prod.xml

# swagger config    
springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs    
  server-url : https://api.ceragem.com/
  swagger-ui:
    path: /ceragem/
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
# as config
as:
  api:
    rest-url: https://asm.ceragem.com
    
jasypt:
  encryptor:
    bean: jasyptStringEncryptor    
 
bos:
  api:
#    rest-url: https://mapone.ceragem.com
    rest-url: https://onemap.ceragem.com
    rental-url: https://vhcgzps4ci.pce.ceragem.com:44300/api/web?sap-client=100
    rental-id: ENC(cK93TgBSHWDrswwbADxy0A==)
    rental_pwd: ENC(fSxeE/4bkQ0boFS6GHAnS75xVLc1RYSN3kdXhgEbj/pbVKkJWTbo+QFOj9bDMekaQg7WFHjKApU=)
  use-event: true

